// =============================================================================
// Mixed-Precision FFT Core – 8-point
// Auto-generated by FFTTemplateGenerator
// Mirrors fft_test.v architecture with per-stage configurable precision.
// Active-low asynchronous reset (negedge rst).
// =============================================================================
`timescale 1ns/1ps

module fft_8_sol0_gen1_core #(
    parameter MAX_N      = 1024,
    parameter ADDR_WIDTH = 10
)(
    input  wire        clk,
    input  wire        rst,     // active-low async reset

    // Control
    input  wire        start,
    output reg         done,

    // External load interface (write input samples, bit-reversed externally)
    input  wire                  ext_wr_en,
    input  wire [ADDR_WIDTH-1:0] ext_wr_addr,
    input  wire [23:0]           ext_wr_data,  // 24-bit unified format

    // External unload interface
    input  wire                  ext_reading,
    input  wire [ADDR_WIDTH-1:0] ext_rd_addr,
    output wire [15:0]           ext_rd_data,  // 16-bit (precision = last stage output)

    // bank_sel driven by top during load/unload
    input  wire                  ext_bank_sel
);

    // =========================================================================
    // FSM states – matches fft_test.v state machine
    // =========================================================================
    localparam IDLE           = 4'd0,
               START_AGU      = 4'd1,
               WAIT_AGU_START = 4'd2,
               READ_A         = 4'd3,
               READ_B         = 4'd4,
               WAIT_A         = 4'd5,
               WAIT_B         = 4'd6,
               WRITE_X        = 4'd7,
               WRITE_Y        = 4'd8,
               WAIT_AGU       = 4'd9,
               EVAL_AGU       = 4'd10,
               DONE_STATE     = 4'd11;

    reg [3:0] state;

    // =========================================================================
    // Per-stage precision localparams (baked in from chromosome)
    // =========================================================================
    localparam STAGE0_MULT_PREC = 0;
    localparam STAGE0_ADD_PREC  = 0;
    localparam STAGE0_OUT_PREC  = 0;
    localparam STAGE1_MULT_PREC = 0;
    localparam STAGE1_ADD_PREC  = 0;
    localparam STAGE1_OUT_PREC  = 0;
    localparam STAGE2_MULT_PREC = 0;
    localparam STAGE2_ADD_PREC  = 0;
    localparam STAGE2_OUT_PREC  = 0;

    // =========================================================================
    // Runtime precision signals (combinational, from curr_stage)
    // =========================================================================
    reg cur_mult_prec;
    reg cur_add_prec;
    reg cur_rd_prec;
    reg cur_wr_prec;

    // =========================================================================
    // AGU
    // =========================================================================
    reg  start_agu_reg;
    reg  next_step_reg;
    wire [ADDR_WIDTH-1:0] idx_a, idx_b, k;
    wire done_stage, done_fft;
    wire [ADDR_WIDTH-1:0] curr_stage;

    dit_fft_agu_variable #(
        .MAX_N     (1024),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) agu (
        .clk          (clk),
        .reset        (rst),
        .start        (start_agu_reg),
        .N            (10'd8),
        .next_step    (next_step_reg),
        .idx_a        (idx_a),
        .idx_b        (idx_b),
        .k            (k),
        .done_stage   (done_stage),
        .done_fft     (done_fft),
        .curr_stage   (curr_stage),
        .twiddle_output()
    );

    // =========================================================================
    // Precision mux
    // =========================================================================
    always @(*) begin
        if (ext_reading) begin
            cur_mult_prec = 1'b0;
            cur_add_prec  = 1'b0;
            cur_rd_prec   = 1'b1;  // Read FFT result at final-stage precision (0=FP4)
            cur_wr_prec   = 1'b0;
        end else begin
            case (curr_stage)
            10'd0: begin
                cur_mult_prec = STAGE0_MULT_PREC;
                cur_add_prec  = STAGE0_ADD_PREC;
                cur_rd_prec   = 1'b1;  // Input always loaded as FP8
                cur_wr_prec   = STAGE0_OUT_PREC;
            end
            10'd1: begin
                cur_mult_prec = STAGE1_MULT_PREC;
                cur_add_prec  = STAGE1_ADD_PREC;
                cur_rd_prec   = STAGE0_OUT_PREC;  // previous stage output precision
                cur_wr_prec   = STAGE1_OUT_PREC;
            end
            10'd2: begin
                cur_mult_prec = STAGE2_MULT_PREC;
                cur_add_prec  = STAGE2_ADD_PREC;
                cur_rd_prec   = STAGE1_OUT_PREC;  // previous stage output precision
                cur_wr_prec   = STAGE2_OUT_PREC;
            end
                default: begin
                    cur_mult_prec = 1'b0; cur_add_prec = 1'b0;
                    cur_rd_prec = 1'b1; cur_wr_prec = 1'b0;
                end
            endcase
        end
    end

    // =========================================================================
    // Twiddle ROM  – precision follows cur_mult_prec
    // =========================================================================
    wire [15:0] twiddle;

    twiddle_factor_unified #(
        .MAX_N     (1024),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) twiddle_rom (
        .k          (k),
        .n          (10'd8),
        .PRECISION  (cur_mult_prec),
        .twiddle_out(twiddle)
    );

    // =========================================================================
    // Memory signals
    // =========================================================================
    // bank_sel: during FFT computation the core owns it;
    //           during IDLE (load) and external read the top drives ext_bank_sel.
    reg  fft_bank_sel;
    wire active_bank_sel = (state == IDLE || ext_reading) ? ext_bank_sel : fft_bank_sel;

    // Read address mux: external read takes priority
    wire [ADDR_WIDTH-1:0] mem_rd_addr = ext_reading ? ext_rd_addr :
                                        (state == READ_A) ? idx_a :
                                        (state == READ_B) ? idx_b : 10'd0;

    // Write mux: external load takes priority; otherwise butterfly results
    wire        mem_wr_en   = ext_wr_en ? 1'b1 :
                              (state == WRITE_X || state == WRITE_Y) ? 1'b1 : 1'b0;

    wire [ADDR_WIDTH-1:0] mem_wr_addr = ext_wr_en ? ext_wr_addr :
                                        (state == WRITE_X) ? idx_a :
                                        (state == WRITE_Y) ? idx_b : 10'd0;

    wire [23:0] mem_wr_data = ext_wr_en ? ext_wr_data :
                              (state == WRITE_X) ? X_wr_24 :
                              (state == WRITE_Y) ? Y_wr_24 : 24'd0;

    wire [15:0] rd_data_16;

    mixed_memory_unified #(
        .n         (1024),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) mem (
        .clk          (clk),
        .rst          (rst),
        .bank_sel     (active_bank_sel),
        .rd_addr_0    (mem_rd_addr),
        .rd_precision_0(cur_rd_prec),
        .rd_data_0    (rd_data_16),
        .wr_en_1      (mem_wr_en),
        .wr_addr_1    (mem_wr_addr),
        .wr_data_1    (mem_wr_data)
    );

    assign ext_rd_data = rd_data_16;

    // =========================================================================
    // Expand 16-bit memory read to 24-bit butterfly inputs
    // =========================================================================
    // Expand 16-bit memory read to 24-bit butterfly input
    // For FP8 reads: rd_data = {fp8_real[7:0], fp8_imag[7:0]} → place at [23:8]
    // For FP4 reads: rd_data = {8'h00, fp4_real[7:4], fp4_imag[3:0]} → place at [7:0]
    // butterfly_wrapper selects the correct slice based on MULT_PRECISION.
    wire [23:0] mem_rd_24;
    assign mem_rd_24 = cur_rd_prec
                       ? {rd_data_16, 8'h00}    // FP8: move to [23:8]
                       : {16'h0000, rd_data_16[7:0]};  // FP4: at [7:0]

    reg [23:0] A_24, B_24;

    // =========================================================================
    // Twiddle ROM already instantiated above
    // =========================================================================

    // =========================================================================
    // Per-stage butterfly instances
    // =========================================================================
    // Per-stage butterfly wrappers (precision baked in)
    wire [15:0] X_st0, Y_st0;
    wire        fp8_out_st0;
    wire [15:0] X_st1, Y_st1;
    wire        fp8_out_st1;
    wire [15:0] X_st2, Y_st2;
    wire        fp8_out_st2;

    butterfly_wrapper #(
        .MULT_PRECISION(0),
        .ADD_PRECISION (0)
    ) bf_st0 (
        .A            (A_24),
        .B            (B_24),
        .W            (twiddle),
        .X            (X_st0),
        .Y            (Y_st0),
        .output_is_fp8(fp8_out_st0)
    );

    butterfly_wrapper #(
        .MULT_PRECISION(0),
        .ADD_PRECISION (0)
    ) bf_st1 (
        .A            (A_24),
        .B            (B_24),
        .W            (twiddle),
        .X            (X_st1),
        .Y            (Y_st1),
        .output_is_fp8(fp8_out_st1)
    );

    butterfly_wrapper #(
        .MULT_PRECISION(0),
        .ADD_PRECISION (0)
    ) bf_st2 (
        .A            (A_24),
        .B            (B_24),
        .W            (twiddle),
        .X            (X_st2),
        .Y            (Y_st2),
        .output_is_fp8(fp8_out_st2)
    );

    // Select butterfly output for the active stage
    reg [15:0] X_bf, Y_bf;
    reg        bf_is_fp8;
    always @(*) begin
        case (curr_stage)
            10'd0: begin X_bf = X_st0; Y_bf = Y_st0; bf_is_fp8 = fp8_out_st0; end
            10'd1: begin X_bf = X_st1; Y_bf = Y_st1; bf_is_fp8 = fp8_out_st1; end
            10'd2: begin X_bf = X_st2; Y_bf = Y_st2; bf_is_fp8 = fp8_out_st2; end
            default: begin X_bf = 16'h0; Y_bf = 16'h0; bf_is_fp8 = 1'b0; end
        endcase
    end

    // =========================================================================
    // Write-back packing (FP4↔FP8 converters)
    // =========================================================================
    reg [15:0] X_reg, Y_reg;
    reg        out_was_fp8;

    // Write-back: always store both FP8 and FP4 slots
    wire [7:0]  X_fp4_packed, Y_fp4_packed;
    wire [15:0] X_fp8_packed, Y_fp8_packed;

    // FP8→FP4 converters (used when butterfly output is FP8)
    fp8_to_fp4_converter conv_xr (.fp8_in(X_reg[15:8]), .fp4_out(X_fp4_packed[7:4]));
    fp8_to_fp4_converter conv_xi (.fp8_in(X_reg[7:0]),  .fp4_out(X_fp4_packed[3:0]));
    fp8_to_fp4_converter conv_yr (.fp8_in(Y_reg[15:8]), .fp4_out(Y_fp4_packed[7:4]));
    fp8_to_fp4_converter conv_yi (.fp8_in(Y_reg[7:0]),  .fp4_out(Y_fp4_packed[3:0]));

    // FP4→FP8 converters (used when butterfly output is FP4)
    fp4_to_fp8_converter conv_xr8 (.fp4_in(X_reg[7:4]), .fp8_out(X_fp8_packed[15:8]));
    fp4_to_fp8_converter conv_xi8 (.fp4_in(X_reg[3:0]), .fp8_out(X_fp8_packed[7:0]));
    fp4_to_fp8_converter conv_yr8 (.fp4_in(Y_reg[7:4]), .fp8_out(Y_fp8_packed[15:8]));
    fp4_to_fp8_converter conv_yi8 (.fp4_in(Y_reg[3:0]), .fp8_out(Y_fp8_packed[7:0]));

    // Final 24-bit write data
    wire [23:0] X_wr_24, Y_wr_24;
    assign X_wr_24 = out_was_fp8 ? {X_reg,       X_fp4_packed}
                                 : {X_fp8_packed, X_reg[7:0]};
    assign Y_wr_24 = out_was_fp8 ? {Y_reg,       Y_fp4_packed}
                                 : {Y_fp8_packed, Y_reg[7:0]};

    // =========================================================================
    // FSM – mirrors fft_test.v
    // =========================================================================
    always @(posedge clk or negedge rst) begin
        if (!rst) begin
            state         <= IDLE;
            start_agu_reg <= 1'b0;
            next_step_reg <= 1'b0;
            fft_bank_sel  <= 1'b0;
            done          <= 1'b0;
            A_24          <= 24'd0;
            B_24          <= 24'd0;
            X_reg         <= 16'd0;
            Y_reg         <= 16'd0;
            out_was_fp8   <= 1'b0;
        end else begin
            case (state)
                // -----------------------------------------------------------
                IDLE: begin
                    done <= 1'b0;
                    if (start) begin
                        fft_bank_sel <= 1'b0; // Stage 0 reads Bank 0, writes Bank 1
                        state        <= START_AGU;
                    end
                end

                // -----------------------------------------------------------
                START_AGU: begin
                    start_agu_reg <= 1'b1;
                    state         <= WAIT_AGU_START;
                end

                WAIT_AGU_START: begin
                    start_agu_reg <= 1'b0;
                    state         <= READ_A;
                end

                // -----------------------------------------------------------
                // 2-cycle synchronous memory read sequence
                // Cycle 1 (READ_A): address idx_a is presented to memory
                // Cycle 2 (READ_B): address idx_b is presented; A data available next cycle
                // Cycle 3 (WAIT_A): A data sampled from rd_data_16
                // Cycle 4 (WAIT_B): B data sampled from rd_data_16
                // -----------------------------------------------------------
                READ_A: begin
                    // mem_rd_addr is idx_a (driven combinationally)
                    state <= READ_B;
                end

                READ_B: begin
                    // mem_rd_addr is idx_b
                    state <= WAIT_A;
                end

                WAIT_A: begin
                    // A data is now stable on rd_data_16
                    A_24  <= mem_rd_24;
                    state <= WAIT_B;
                end

                WAIT_B: begin
                    // B data is now stable on rd_data_16
                    B_24        <= mem_rd_24;
                    // Capture butterfly outputs (combinational from A_24/B_24)
                    X_reg       <= X_bf;
                    Y_reg       <= Y_bf;
                    out_was_fp8 <= bf_is_fp8;
                    state       <= WRITE_X;
                end

                // -----------------------------------------------------------
                WRITE_X: begin
                    // mem_wr_en=1, write X_wr_24 to idx_a  (combinational)
                    state <= WRITE_Y;
                end

                WRITE_Y: begin
                    // mem_wr_en=1, write Y_wr_24 to idx_b
                    next_step_reg <= 1'b1;
                    state         <= WAIT_AGU;
                end

                WAIT_AGU: begin
                    next_step_reg <= 1'b0;
                    state         <= EVAL_AGU;
                end

                EVAL_AGU: begin
                    if (done_fft) begin
                        // After 3 stages (each stage flips bank), result is in bank 1
                        fft_bank_sel <= 1'b1;
                        state        <= DONE_STATE;
                    end else if (done_stage) begin
                        fft_bank_sel <= ~fft_bank_sel; // Ping-pong
                        state        <= READ_A;
                    end else begin
                        state        <= READ_A;
                    end
                end

                // -----------------------------------------------------------
                DONE_STATE: begin
                    done <= 1'b1;
                    if (!start) state <= IDLE;
                end

                default: state <= IDLE;
            endcase
        end
    end

endmodule
