// =============================================================================
// Mixed-Precision FFT TOP – 8-point
// Instantiates: fft_8_sol1_gen1_core
// Auto-generated by FFTTemplateGenerator
//
// Interface mirrors tb_fft_test.v exactly:
//   load_en / load_addr / load_data   → write input samples
//   start / done                      → FFT trigger / completion
//   unload_en / unload_addr / unload_data → read FFT results
// =============================================================================
`timescale 1ns/1ps

module fft_8_sol1_gen1_top (
    input  wire        clk,
    input  wire        rst,     // active-low async reset

    // Control
    input  wire        start,
    output reg         done,

    // Load interface  (load_data is 16-bit FP8: {real[7:0], imag[7:0]})
    input  wire              load_en,
    input  wire [2:0]  load_addr,
    input  wire [15:0]       load_data,

    // Unload interface (2-cycle read latency)
    input  wire              unload_en,
    input  wire [2:0]  unload_addr,
    output wire [15:0]       unload_data
);

    // -------------------------------------------------------------------------
    // Bit-reversal for load addressing
    // -------------------------------------------------------------------------
    wire [9:0] load_addr_rev;

    bit_reverse #(
        .MAX_N(1024),
        .WIDTH(10)
    ) br (
        .in  ({{ 7'b0, load_addr }}),
        .N   (10'd8),
        .out (load_addr_rev)
    );

    // -------------------------------------------------------------------------
    // Bank-select management
    //   IDLE / loading : bank_sel = 1'b1 (so writes go to Bank 0)
    //   During FFT     : core manages internally
    //   After FFT      : bank_sel = 3[0] ? 1'b1 : 1'b0
    //                    (result ends up in bank = num_stages MOD 2)
    // -------------------------------------------------------------------------
    reg bank_sel;

    // -------------------------------------------------------------------------
    // Core instantiation
    // -------------------------------------------------------------------------
    wire        core_done;
    wire [15:0] core_rd_data;

    fft_8_sol1_gen1_core #(
        .MAX_N     (1024),
        .ADDR_WIDTH(10)
    ) core (
        .clk          (clk),
        .rst          (rst),
        .start        (start),
        .done         (core_done),

        // Load: bit-reversed address, data packed into 24-bit unified format
        // We always load as FP8 (upper 16 bits of 24-bit word)
        .ext_wr_en    (load_en),
        .ext_wr_addr  (load_addr_rev),
        .ext_wr_data  ({ load_data, 8'h00 }),  // FP8 in [23:8], FP4=0 in [7:0]

        // Unload
        .ext_reading  (unload_en),
        .ext_rd_addr  ({{ 7'b0, unload_addr }}),
        .ext_rd_data  (core_rd_data),

        .ext_bank_sel (bank_sel)
    );

    assign unload_data = core_rd_data;

    // -------------------------------------------------------------------------
    // done register – mirrors fft_test.v behaviour
    // -------------------------------------------------------------------------
    always @(posedge clk or negedge rst) begin
        if (!rst) begin
            done     <= 1'b0;
            bank_sel <= 1'b1;
        end else begin
            if (start) begin
                done     <= 1'b0;
                bank_sel <= 1'b1; // Core will manage bank during FFT
            end else if (core_done) begin
                done     <= 1'b1;
                // Result bank after 3 stages (each stage flips):
                //   odd  num_stages → result in bank 1 (bank_sel=1 to read from bank 1)
                //   even num_stages → result in bank 0 (bank_sel=0 to read from bank 0)
                bank_sel <= 1'b1;  // Result in bank 1 after 3 stage flips
            end else if (!start && done) begin
                done <= 1'b0;
            end
        end
    end

endmodule
