// Mixed-Precision FFT Core – 8-point
// Auto-generated by FFTTemplateGenerator
// Memory : 24-bit unified [23:16]=FP8_real [15:8]=FP8_imag [7:4]=FP4_real [3:0]=FP4_imag
// I/O bus: 16-bit per data point (FP8) or 8-bit (FP4) inside 16-bit zero-padded

`timescale 1ns/1ps

module mixed_fft_8_core #(
    parameter MAX_N     = 8,
    parameter ADDR_WIDTH = 3
)(
    input  wire clk,
    input  wire rst,
    input  wire start,
    input  wire [ADDR_WIDTH-1:0] N,
    output reg  done,
    output reg  error,

    // External write interface (load input samples)
    input  wire                  ext_wr_en,
    input  wire [ADDR_WIDTH-1:0] ext_wr_addr,
    input  wire [23:0]           ext_wr_data,
    input  wire                  ext_bank_sel,

    // External read interface (unload FFT results)
    input  wire [ADDR_WIDTH-1:0] ext_rd_addr,
    input  wire                  ext_reading,
    output wire [23:0]           rd_data_0       // full 24-bit for host
);

    // ----------------------------------------------------------------
    // State machine encoding
    // ----------------------------------------------------------------
    localparam IDLE    = 4'd0;
    localparam INIT    = 4'd1;
    localparam READ_A  = 4'd2;
    localparam WAIT_1  = 4'd3;
    localparam WAIT_A  = 4'd4;
    localparam READ_B  = 4'd5;
    localparam WAIT_2  = 4'd6;
    localparam WAIT_B  = 4'd7;
    localparam COMPUTE = 4'd8;
    localparam WRITE_X = 4'd9;
    localparam WRITE_Y = 4'd10;
    localparam DONE    = 4'd11;

    reg [3:0] state, next_state;

    // ----------------------------------------------------------------
    // Per-stage precision localparams (from chromosome)
    // ----------------------------------------------------------------
    localparam STAGE0_MULT_PREC = 1;
    localparam STAGE0_ADD_PREC  = 0;
    localparam STAGE0_OUT_PREC  = 1;
    localparam STAGE0_RD_PREC   = 0;
    localparam STAGE1_MULT_PREC = 1;
    localparam STAGE1_ADD_PREC  = 0;
    localparam STAGE1_OUT_PREC  = 1;
    localparam STAGE1_RD_PREC   = 1;
    localparam STAGE2_MULT_PREC = 0;
    localparam STAGE2_ADD_PREC  = 0;
    localparam STAGE2_OUT_PREC  = 0;
    localparam STAGE2_RD_PREC   = 1;

    // ----------------------------------------------------------------
    // Runtime precision control registers (set by combinational mux)
    // ----------------------------------------------------------------
    reg current_mult_prec;  // 0=FP4 1=FP8 – drives butterfly select
    reg current_add_prec;   // 0=FP4 1=FP8 – drives butterfly select
    reg memory_read_prec;   // precision to read FROM memory this stage
    reg memory_write_prec;  // precision that butterfly output is in

    // ----------------------------------------------------------------
    // AGU
    // ----------------------------------------------------------------
    reg agu_next_step;
    wire [ADDR_WIDTH-1:0] idx_a, idx_b, k;
    wire agu_done_stage, agu_done_fft;
    wire [2-1:0] curr_stage;

    dit_fft_agu_variable #(
        .MAX_N     (MAX_N),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) agu_inst (
        .clk          (clk),
        .reset        (rst),
        .N            (N),
        .next_step    (agu_next_step),
        .idx_a        (idx_a),
        .idx_b        (idx_b),
        .k            (k),
        .done_stage   (agu_done_stage),
        .done_fft     (agu_done_fft),
        .curr_stage   (curr_stage),
        .twiddle_output()
    );

    // ----------------------------------------------------------------
    // Precision mux: set *_prec regs from curr_stage
    // ----------------------------------------------------------------
    always @(*) begin
        case (curr_stage)
            2'd0: begin
                current_mult_prec  = STAGE0_MULT_PREC;
                current_add_prec   = STAGE0_ADD_PREC;
                memory_read_prec   = STAGE0_RD_PREC;
                memory_write_prec  = STAGE0_OUT_PREC;
            end
            2'd1: begin
                current_mult_prec  = STAGE1_MULT_PREC;
                current_add_prec   = STAGE1_ADD_PREC;
                memory_read_prec   = STAGE1_RD_PREC;
                memory_write_prec  = STAGE1_OUT_PREC;
            end
            2'd2: begin
                current_mult_prec  = STAGE2_MULT_PREC;
                current_add_prec   = STAGE2_ADD_PREC;
                memory_read_prec   = STAGE2_RD_PREC;
                memory_write_prec  = STAGE2_OUT_PREC;
            end
            default: begin
                current_mult_prec = 0;
                current_add_prec  = 0;
                memory_read_prec  = 0;
                memory_write_prec = 0;
            end
        endcase
    end

    // ----------------------------------------------------------------
    // Memory signals
    // ----------------------------------------------------------------
    reg  [ADDR_WIDTH-1:0] int_rd_addr;
    wire [15:0]           int_rd_data_16;  // 16-bit from memory (precision-sliced)
    wire [23:0]           int_rd_data_24;  // 24-bit full read (for external host)
    reg  int_wr_en;
    reg  [ADDR_WIDTH-1:0] int_wr_addr;
    reg  [23:0]           int_wr_data;

    // Arbitrate between external and internal access
    wire final_wr_en                  = ext_wr_en | int_wr_en;
    wire [ADDR_WIDTH-1:0] final_wr_addr = ext_wr_en ? ext_wr_addr : int_wr_addr;
    wire [23:0]           final_wr_data = ext_wr_en ? ext_wr_data : int_wr_data;
    wire [ADDR_WIDTH-1:0] final_rd_addr = ext_reading ? ext_rd_addr : int_rd_addr;

    // Ping-pong bank control
    reg fft_bank_sel;
    wire active_bank_sel = ext_reading                               ? ext_bank_sel :
                           (state == IDLE)                           ? ext_bank_sel :
                           fft_bank_sel;

    // Unified memory (stores 24-bit; returns 16-bit slice via rd_precision_0)
    mixed_memory_unified #(
        .n         (MAX_N),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) memory_inst (
        .clk         (clk),
        .rst         (rst),
        .bank_sel    (active_bank_sel),
        .rd_addr_0   (final_rd_addr),
        .rd_precision_0(memory_read_prec),  // ← set by precision mux
        .rd_data_0   (int_rd_data_16),      // 16-bit sliced output
        .wr_en_1     (final_wr_en),
        .wr_addr_1   (final_wr_addr),
        .wr_data_1   (final_wr_data)        // 24-bit write (canonical format)
    );

    // Full 24-bit read for external host (re-read without precision slicing)
    // We expose the same 16-bit data zero-extended as 24-bit for the top module.
    assign int_rd_data_24 = memory_read_prec
                            ? {int_rd_data_16, 8'h00}
                            : {16'h0000, int_rd_data_16[7:0]};
    assign rd_data_0 = int_rd_data_24;

    // ----------------------------------------------------------------
    // Expand 16-bit memory read to 24-bit butterfly input bus
    // ----------------------------------------------------------------
    // 16-bit memory read → 24-bit butterfly bus
    // mixed_memory_unified already applies rd_precision_0, returning 16 bits.
    // We re-pack into the 24-bit canonical format so butterfly_wrapper_16bit
    // can slice consistently: [23:8]=FP8 complex, [7:0]=FP4 complex.
    wire [15:0] mem_rd_16;   // raw 16-bit output of the memory
    assign mem_rd_16 = int_rd_data_16;  // driven by memory instance below

    // Expand to 24-bit for butterfly input
    // FP8 path: memory returns {fp8_real[7:0], fp8_imag[7:0]} in [15:0]
    //           → place in [23:8], pad [7:0] with 0
    // FP4 path: memory returns {8'h00, fp4_real[3:0], fp4_imag[3:0]} in [15:0]
    //           → only [7:0] matters; place in [7:0], pad [23:8] with 0
    wire [23:0] mem_rd_24;
    assign mem_rd_24 = memory_read_prec
                       ? {mem_rd_16[15:0], 8'h00}   // FP8: pack into [23:8]
                       : {16'h0000, mem_rd_16[7:0]}; // FP4: pack into [7:0]

    // A_mem_24 / B_mem_24 are what butterfly instances see
    reg [23:0] A_mem_24, B_mem_24;

    // ----------------------------------------------------------------
    // Per-stage twiddle ROM instances
    // ----------------------------------------------------------------
    // Single twiddle ROM instance — precision is a runtime input port.
    // The ROM stores all twiddle factors in both precisions in each
    // 24-bit entry; the precision input just selects the output slice.
    wire [15:0] twiddle;

    twiddle_factor_unified #(
        .MAX_N     (8),
        .ADDR_WIDTH(3)
    ) twiddle_inst (
        .k           (k),
        .n           (N),
        .PRECISION   (current_mult_prec),  // driven by stage mux
        .twiddle_out (twiddle)
    );

    // ----------------------------------------------------------------
    // Per-stage butterfly instances
    // ----------------------------------------------------------------
    // Per-stage butterfly instances (precision set from chromosome)
    wire [15:0] X_stage0, Y_stage0;
    wire        fp8_out_stage0;
    wire [15:0] X_stage1, Y_stage1;
    wire        fp8_out_stage1;
    wire [15:0] X_stage2, Y_stage2;
    wire        fp8_out_stage2;

    generate
        // Stage 0: mult=1 add=0
        butterfly_wrapper #(
            .MULT_PRECISION(1),
            .ADD_PRECISION (0)
        ) bf_stage0_inst (
            .A        (A_mem_24),
            .B        (B_mem_24),
            .W            (twiddle),
            .X            (X_stage0),
            .Y            (Y_stage0),
            .output_is_fp8(fp8_out_stage0)
        );

        // Stage 1: mult=1 add=0
        butterfly_wrapper #(
            .MULT_PRECISION(1),
            .ADD_PRECISION (0)
        ) bf_stage1_inst (
            .A        (A_mem_24),
            .B        (B_mem_24),
            .W            (twiddle),
            .X            (X_stage1),
            .Y            (Y_stage1),
            .output_is_fp8(fp8_out_stage1)
        );

        // Stage 2: mult=0 add=0
        butterfly_wrapper #(
            .MULT_PRECISION(0),
            .ADD_PRECISION (0)
        ) bf_stage2_inst (
            .A        (A_mem_24),
            .B        (B_mem_24),
            .W            (twiddle),
            .X            (X_stage2),
            .Y            (Y_stage2),
            .output_is_fp8(fp8_out_stage2)
        );

    endgenerate

    // Select active butterfly output based on curr_stage
    reg [15:0] X_bf, Y_bf;
    reg        bf_output_is_fp8;
    always @(*) begin
        case (curr_stage)
            0: begin
                X_bf            = X_stage0;
                Y_bf            = Y_stage0;
                bf_output_is_fp8 = fp8_out_stage0;
            end
            1: begin
                X_bf            = X_stage1;
                Y_bf            = Y_stage1;
                bf_output_is_fp8 = fp8_out_stage1;
            end
            2: begin
                X_bf            = X_stage2;
                Y_bf            = Y_stage2;
                bf_output_is_fp8 = fp8_out_stage2;
            end
            default: begin X_bf = 0; Y_bf = 0; bf_output_is_fp8 = 0; end
        endcase
    end

    // ----------------------------------------------------------------
    // FP4 ↔ FP8 conversion wires for write-back packing
    // ----------------------------------------------------------------
    // Convert the 16-bit butterfly output both ways so we can write
    // the canonical 24-bit word regardless of output precision.
    wire [7:0]  X_bf_fp4_real, X_bf_fp4_imag;
    wire [7:0]  Y_bf_fp4_real, Y_bf_fp4_imag;
    wire [15:0] X_bf_fp8_expanded, Y_bf_fp8_expanded;

    // FP8→FP4 conversion (used when output is FP8, to fill FP4 field)
    fp8_to_fp4_converter conv_x_fp8_to_fp4_real (.fp8_in(X_bf[15:8]), .fp4_out(X_bf_fp4_real[7:4]));
    fp8_to_fp4_converter conv_x_fp8_to_fp4_imag (.fp8_in(X_bf[7:0]),  .fp4_out(X_bf_fp4_real[3:0]));
    fp8_to_fp4_converter conv_y_fp8_to_fp4_real (.fp8_in(Y_bf[15:8]), .fp4_out(Y_bf_fp4_real[7:4]));
    fp8_to_fp4_converter conv_y_fp8_to_fp4_imag (.fp8_in(Y_bf[7:0]),  .fp4_out(Y_bf_fp4_real[3:0]));

    // FP4→FP8 conversion (used when output is FP4, to fill FP8 field)
    fp4_to_fp8_converter conv_x_fp4_to_fp8_real (.fp4_in(X_bf[7:4]), .fp8_out(X_bf_fp8_expanded[15:8]));
    fp4_to_fp8_converter conv_x_fp4_to_fp8_imag (.fp4_in(X_bf[3:0]), .fp8_out(X_bf_fp8_expanded[7:0]));
    fp4_to_fp8_converter conv_y_fp4_to_fp8_real (.fp4_in(Y_bf[7:4]), .fp8_out(Y_bf_fp8_expanded[15:8]));
    fp4_to_fp8_converter conv_y_fp4_to_fp8_imag (.fp4_in(Y_bf[3:0]), .fp8_out(Y_bf_fp8_expanded[7:0]));

    // ----------------------------------------------------------------
    // Registered butterfly results and output precision flag
    // ----------------------------------------------------------------
    reg [15:0] X_reg, Y_reg;
    reg        output_was_fp8;

    // ----------------------------------------------------------------
    // Stage completion (rising-edge detect on agu_done_stage)
    // ----------------------------------------------------------------
    reg prev_done_stage;
    wire stage_complete = agu_done_stage && !prev_done_stage;

    // ----------------------------------------------------------------
    // Main state machine – sequential
    // ----------------------------------------------------------------
    always @(posedge clk or negedge rst) begin
        if (!rst) begin
            state          <= IDLE;
            done           <= 0;
            error          <= 0;
            A_mem_24       <= 0;
            B_mem_24       <= 0;
            X_reg          <= 0;
            Y_reg          <= 0;
            output_was_fp8 <= 0;
            int_rd_addr    <= 0;
            int_wr_en      <= 0;
            int_wr_addr    <= 0;
            int_wr_data    <= 0;
            agu_next_step  <= 0;
            fft_bank_sel   <= 0;
            prev_done_stage <= 0;
        end else begin
            state           <= next_state;
            int_wr_en       <= 0;
            agu_next_step   <= 0;
            prev_done_stage <= agu_done_stage;

            // Flip ping-pong bank on stage completion
            if (stage_complete && state != IDLE && state != DONE)
                fft_bank_sel <= ~fft_bank_sel;

            case (state)
                IDLE: begin
                    done  <= 0;
                    error <= 0;
                    fft_bank_sel <= 0;
                    if (start && (N > MAX_N || (N & (N - 1)) != 0))
                        error <= 1;
                end

                INIT: begin
                    // No operation; AGU will start from reset state
                end

                READ_A: begin
                    int_rd_addr <= idx_a;
                end

                WAIT_1: begin 
                end

                WAIT_A: begin
                    // Memory has 1-cycle read latency; data available next cycle
                end

                READ_B: begin
                    // Latch A from memory read port, start reading B
                    // Reconstruct 24-bit from the 16-bit memory output
                    A_mem_24    <= mem_rd_24;
                    int_rd_addr <= idx_b;
                end

                WAIT_2: begin 
                end

                WAIT_B: begin
                    // Waiting for B read to complete
                end

                COMPUTE: begin
                    // Latch B; butterfly combinationally computes X_bf, Y_bf
                    B_mem_24        <= mem_rd_24;
                    X_reg           <= X_bf;
                    Y_reg           <= Y_bf;
                    output_was_fp8  <= bf_output_is_fp8;
                end

                WRITE_X: begin
                    int_wr_en   <= 1;
                    int_wr_addr <= idx_a;
                    // Pack 24-bit canonical word from butterfly output
                    if (output_was_fp8) begin
                        // FP8 result: fill [23:8] with FP8 data, [7:0] with FP4 downcast
                        int_wr_data <= {X_reg,          X_bf_fp4_real[7:4], X_bf_fp4_real[3:0]};
                    end else begin
                        // FP4 result: fill [7:0] with FP4 data, [23:8] with FP8 upcast
                        int_wr_data <= {X_bf_fp8_expanded, X_reg[7:0]};
                    end
                end

                WRITE_Y: begin
                    int_wr_en   <= 1;
                    int_wr_addr <= idx_b;
                    if (output_was_fp8) begin
                        int_wr_data <= {Y_reg,          Y_bf_fp4_real[7:4], Y_bf_fp4_real[3:0]};
                    end else begin
                        int_wr_data <= {Y_bf_fp8_expanded, Y_reg[7:0]};
                    end
                    agu_next_step <= 1;
                end

                DONE: begin
                    done <= 1;
                end
            endcase
        end
    end

    // ----------------------------------------------------------------
    // Next-state logic
    // ----------------------------------------------------------------
    always @(*) begin
        next_state = state;
        case (state)
            IDLE   : if (start && !error) next_state = INIT;
            INIT   : next_state = READ_A;
            READ_A : next_state = WAIT_1;
            WAIT_1 : next_state = WAIT_A; 
            WAIT_A : next_state = READ_B;
            READ_B : next_state = WAIT_2;
            WAIT_2 : next_state = WAIT_B;
            WAIT_B : next_state = COMPUTE;
            COMPUTE: next_state = WRITE_X;
            WRITE_X: next_state = WRITE_Y;
            WRITE_Y: next_state = agu_done_fft ? DONE : READ_A;
            DONE   : next_state = IDLE;
            default: next_state = IDLE;
        endcase
    end

endmodule
