// Mixed-precision FFT TOP – 8-point
// Instantiates: fft_8_sol4_gen1_core
// Auto-generated by FFTTemplateGenerator

`timescale 1ns/1ps

module fft_8_sol4_gen1_top #(
    parameter MAX_N      = 1024,
    parameter ADDR_WIDTH = 10
)(
    input  wire        clk,
    input  wire        rst,
    input wire [ADDR_WIDTH-1:0] N,
    // Input interface
    input  wire        data_in_valid,
    input  wire [23:0] data_in,
    output reg         fft_ready,

    // Output interface
    output reg         data_out_valid,
    output reg  [23:0] data_out,

    // Status
    output wire        done,
    output wire        error
);

    reg [ADDR_WIDTH-1:0] wr_addr, rd_addr;
    reg                  wr_en;
    wire [23:0]          rd_data;
    wire                 fft_done;

    // Bit-reversal on write address
    wire [ADDR_WIDTH-1:0] wr_addr_reversed;
    bit_reverse #(
        .MAX_N(1024),
        .WIDTH(ADDR_WIDTH)
    ) bit_rev (
        .in (wr_addr),
        .out(wr_addr_reversed)
    );

    // State machine
    localparam MEM_IDLE    = 2'd0;
    localparam MEM_WRITE   = 2'd1;
    localparam MEM_PROCESS = 2'd2;
    localparam MEM_READ    = 2'd3;

    reg [1:0]            mem_state, mem_next_state;
    reg [ADDR_WIDTH-1:0] input_count, output_count;
    reg [ADDR_WIDTH-1:0] rd_addr_count; // tracks addresses issued to memory
    reg                  fft_start, fft_start_issued;
    reg                  ext_reading;
    reg                  read_bank_sel;

    localparam NUM_STAGES = 3;

    wire core_bank_sel = (mem_state == MEM_READ)  ? read_bank_sel :
                         (mem_state == MEM_WRITE ||
                          mem_state == MEM_IDLE)  ? 1'b1 : 1'b0;

    // FFT core (precision baked-in per chromosome)
    fft_8_sol4_gen1_core #(
        .MAX_N     (MAX_N),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) fft_core (
        .clk        (clk),
        .rst        (rst),
        .start      (fft_start),
        .N          (N),
        .done       (fft_done),
        .error      (error),
        .ext_wr_en  (wr_en),
        .ext_wr_addr(wr_addr_reversed),
        .ext_wr_data(data_in),
        .ext_bank_sel(core_bank_sel),
        .ext_rd_addr (rd_addr),
        .ext_reading (ext_reading),
        .rd_data_0   (rd_data)
    );

    // Next-state logic
    always @(*) begin
        mem_next_state = mem_state;
        case (mem_state)
            MEM_IDLE:    if (data_in_valid)                          mem_next_state = MEM_WRITE;
            MEM_WRITE:   if (input_count >= N)                       mem_next_state = MEM_PROCESS;
            MEM_PROCESS: if (fft_done)                               mem_next_state = MEM_READ;
            // Transition only after all N outputs have been emitted
            MEM_READ:    if (output_count >= N && rd_addr_count >= N) mem_next_state = MEM_IDLE;
        endcase
    end

    always @(posedge clk or negedge rst) begin
        if (!rst) begin
            mem_state        <= MEM_IDLE;
            input_count      <= 0;
            output_count     <= 0;
            rd_addr_count    <= 0;
            wr_en            <= 0;
            wr_addr          <= 0;
            rd_addr          <= 0;
            fft_ready        <= 1;
            data_out_valid   <= 0;
            data_out         <= 0;
            fft_start        <= 0;
            fft_start_issued <= 0;
            read_bank_sel    <= 0;
            ext_reading      <= 0;
        end else begin
            mem_state <= mem_next_state;
            fft_start <= 0;

            case (mem_state)
                MEM_IDLE: begin
                    fft_ready        <= 1;
                    input_count      <= 0;
                    output_count     <= 0;
                    rd_addr_count    <= 0;
                    data_out_valid   <= 0;
                    fft_start_issued <= 0;
                    ext_reading      <= 0;
                    if (data_in_valid) begin
                        wr_en       <= 1;
                        wr_addr     <= 0;
                        input_count <= 1;
                        fft_ready   <= 0;
                    end else begin
                        wr_en <= 0;
                    end
                end

                MEM_WRITE: begin
                    if (input_count < N && data_in_valid) begin
                        wr_en       <= 1;
                        wr_addr     <= input_count;
                        input_count <= input_count + 1;
                    end else if (input_count >= N) begin
                        wr_en <= 0;
                        if (!fft_start_issued) begin
                            fft_start        <= 1;
                            fft_start_issued <= 1;
                        end
                    end else begin
                        wr_en <= 0;
                    end
                end

                MEM_PROCESS: begin
                    wr_en       <= 0;
                    ext_reading <= 0;  // core owns memory; external reads not active
                    if (fft_done) begin
                        output_count  <= 0;
                        rd_addr_count <= 0;
                        // After NUM_STAGES ping-pong flips, result is in bank NUM_STAGES[0]
                        read_bank_sel <= NUM_STAGES[0];
                    end
                end

                MEM_READ: begin
                    // Memory (mixed_memory_unified) has 2-cycle read latency:
                    //   cycle 0: address registered by memory
                    //   cycle 1: data fetched from array into rd_data_full
                    //   cycle 2: precision slice applied → rd_data valid
                    //
                    // Strategy: issue all N addresses first (rd_addr_count 0..N-1),
                    // then collect N outputs after the 2-cycle pipeline fills.
                    // output_count counts valid data_out_valid pulses emitted.
                    //
                    // Timeline:
                    //   rd_addr_count: 0  1  2  3  4  5  6  7  8  8  8
                    //   rd_addr       : 0  1  2  3  4  5  6  7  -  -  -
                    //   data valid    : -  -  x0 x1 x2 x3 x4 x5 x6 x7 -
                    //   output_count  : 0  0  0  1  2  3  4  5  6  7  8 -> IDLE

                    ext_reading <= 1;

                    // Phase 1: keep issuing next read address while more to fetch
                    if (rd_addr_count < N) begin
                        rd_addr       <= rd_addr_count;
                        rd_addr_count <= rd_addr_count + 1;
                    end

                    // Phase 2: after 2-cycle pipeline delay, data becomes valid
                    // rd_addr_count reaches 2 means addr 0 was issued 2 cycles ago
                    if (rd_addr_count >= 2 && output_count < N) begin
                        data_out       <= rd_data;
                        data_out_valid <= 1;
                        output_count   <= output_count + 1;
                    end else begin
                        data_out_valid <= 0;
                    end

                    // Stop driving ext_reading once all addresses issued
                    if (rd_addr_count >= N && output_count >= N)
                        ext_reading <= 0;
                end
            endcase
        end
    end

    assign done = fft_done;

endmodule
